using System;
using System.Collections.Generic;
using System.Linq;

namespace Win11Optimizer
{
    public static class TweakCatalog
    {
        // Factory shorthand — keeps the list readable
        private static TweakEntry E(string cat, string icon, bool on, string key,
                                    string name, string desc, string what)
            => new TweakEntry { Category=cat, Icon=icon, DefaultOn=on,
                                TweakKey=key, Name=name, Description=desc, WhatItChanges=what };
        private static TweakEntry Adv(string icon, string advKey, string tweakKey,
                                      string name, string desc, string what)
            => new TweakEntry { Category="Advanced", Icon=icon, DefaultOn=false,
                                IsAdvanced=true, AdvancedKey=advKey, TweakKey=tweakKey,
                                Name=name, Description=desc, WhatItChanges=what };

        public static readonly List<TweakEntry> All = new List<TweakEntry>
        {
            E("Performance","⚡",true,"Perf_PowerPlan",
                "High Performance Power Plan",
                "Switches power plan to maximum performance mode",
                "Runs: powercfg -setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"),
            E("Performance","🔋",true,"Perf_PowerThrottle",
                "Disable Power Throttling",
                "Prevents Windows throttling background CPU usage",
                "Sets HKLM\\...\\PowerThrottling → PowerThrottlingOff = 1"),
            E("Performance","🗂",true,"Perf_SysMain",
                "Disable SysMain (Superfetch)",
                "Stops preloading rarely-used apps into RAM",
                "sc config SysMain start=disabled + net stop SysMain\nSysMain preloads apps it predicts you'll use, consuming RAM and disk I/O. On SSDs the benefit is negligible."),
            E("Performance","🔍",true,"Perf_WSearch",
                "Disable Windows Search Indexer",
                "Removes background disk I/O from search indexing",
                "sc config WSearch start=disabled + net stop WSearch\nKills the background indexing service. Start menu search still works, just slower on first query."),
            E("Performance","⏱",true,"Perf_StartupDelay",
                "Remove Startup Delay",
                "Eliminates the artificial Explorer startup pause",
                "Sets HKCU\\...\\Explorer\\Serialize → StartupDelayInMSec = 0"),
            E("Performance","🖼",true,"Perf_VisualFX",
                "Visual Effects: Best Performance",
                "Turns off animations, shadows and fancy rendering",
                "Sets HKCU\\...\\VisualEffects → VisualFXSetting = 2"),
            E("Performance","📁",true,"Perf_NtfsLastAccess",
                "Disable NTFS Last-Access Timestamps",
                "Reduces filesystem writes on every file read",
                "Runs: fsutil behavior set disablelastaccess 1"),
            E("Performance","📄",true,"Perf_8Dot3",
                "Disable 8.3 Filenames",
                "Removes legacy short filename generation on NTFS",
                "Runs: fsutil behavior set disable8dot3 1"),
            E("Performance","💤",true,"Perf_Hibernate",
                "Disable Hibernation",
                "Frees several GB of disk space, speeds shutdown",
                "Runs: powercfg -h off"),
            E("Performance","🧠",true,"Perf_MemCompression",
                "Disable Memory Compression",
                "Reduces CPU overhead when RAM is under pressure",
                "Runs: Disable-MMAgent -MemoryCompression + Disable-MMAgent -PageCombining (PowerShell)\nPage combining wastes CPU cycles merging identical RAM pages — low value on 16GB+ systems."),
            E("Performance","⏰",true,"Perf_TimerRes",
                "Global 1ms Timer Resolution",
                "Lets games' 1ms timer requests apply system-wide again (Win11 22H2+)",
                "Sets GlobalTimerResolutionRequests = 1 in Session Manager\\kernel\nSince Windows 11 22H2, a timer-resolution request from a minimised or background app no longer applies globally. This restores the old behaviour so tools/games that request 1ms keep it. Raises idle power draw — skip this on laptops."),

            E("Privacy","📡",true,"Priv_Telemetry",
                "Disable Telemetry",
                "Blocks Microsoft data collection at the registry level",
                "Sets AllowTelemetry = 0 in both machine and policy DataCollection keys"),
            E("Privacy","🛑",true,"Priv_DiagTrack",
                "Disable DiagTrack Service",
                "Stops the Connected User Experiences telemetry service",
                "Disables services: DiagTrack, dmwappushservice, RetailDemo, WerSvc"),
            E("Privacy","📢",true,"Priv_AdvertisingId",
                "Disable Advertising ID",
                "Prevents apps from accessing your ad tracking ID",
                "Sets AdvertisingInfo → Enabled = 0 (user) + DisabledByGroupPolicy = 1 (machine)"),
            E("Privacy","🔎",true,"Priv_BingStart",
                "Disable Bing in Start Menu",
                "Removes web search results from the Start search bar",
                "Sets DisableSearchBoxSuggestions = 1 + BingSearchEnabled = 0"),
            E("Privacy","🎙",true,"Priv_Cortana",
                "Disable Cortana Consent",
                "Turns off Cortana data collection consent flag",
                "Sets CortanaConsent = 0 in HKCU\\...\\Search"),
            E("Privacy","📊",true,"Priv_ActivityFeed",
                "Disable Activity Feed",
                "Stops Windows logging app and file activity history",
                "Sets EnableActivityFeed = 0, PublishUserActivities = 0, UploadUserActivities = 0"),
            E("Privacy","📍",true,"Priv_Location",
                "Disable Location Tracking",
                "Blocks apps from accessing your physical location",
                "Sets DisableLocation = 1 in LocationAndSensors policy key"),
            E("Privacy","📷",true,"Priv_Camera",
                "Block App Camera Access",
                "Prevents UWP apps from using the webcam by default",
                "Sets LetAppsAccessCamera = 2 (Force Deny) in AppPrivacy policy"),
            E("Privacy","⚠",true,"Priv_WER",
                "Disable Windows Error Reporting",
                "Stops crash dumps and reports being sent to Microsoft",
                "Sets WER\\Disabled = 1 + disables WER\\QueueReporting scheduled task\nPrevents crash reports being uploaded even when WerSvc is disabled, since the QueueReporting scheduled task can still fire independently."),
            E("Privacy","🛡",true,"Priv_SmartScreen",
                "Disable SmartScreen (Explorer)",
                "Removes SmartScreen cloud checks in File Explorer",
                "Sets EnableSmartScreen = 0 in Windows System policy"),
            E("Privacy","🗓",true,"Priv_TelemetryTasks",
                "Disable Scheduled Telemetry Tasks",
                "Kills CEIP, AppraiserV2, Proxy, DiskDiag, DiagnosticInvoker & push notification tasks",
                "Disables 9 scheduled tasks: Application Experience, Autochk, CEIP, DiskDiagnostic, Diagnosis\\Scheduled, WindowsUpdate\\Automatic App Update, Push Notifications\\LockApplicationComponent"),
            E("Privacy","👁",true,"Priv_AppTracking",
                "Disable App Launch Tracking",
                "Stops Windows logging which apps you open and when",
                "Sets Start_TrackProgs = 0 in Explorer Advanced"),
            E("Privacy","💬",true,"Priv_Feedback",
                "Disable Feedback Requests",
                "Prevents Windows asking you to rate/review features",
                "Sets NumberOfSIUFInPeriod = 0 in HKCU\\...\\Siuf\\Rules"),
            E("Privacy","💬",true,"Priv_ChatIcon",
                "Disable Chat / Teams Taskbar Icon",
                "Removes the Teams/Chat pinned icon from the taskbar",
                "Sets TaskbarMn = 0 in Explorer Advanced"),
            E("Privacy","🤖",true,"Priv_Recall",
                "Disable Windows Recall",
                "Kills AI screenshot feature on Copilot+ PCs (no-op otherwise)",
                "Sets DisableAIDataAnalysis = 1 in both machine and user WindowsAI policy keys"),
            E("Privacy","✨",true,"Priv_Copilot",
                "Disable Windows Copilot",
                "Blocks Copilot from launching and removes its background presence",
                "Sets TurnOffWindowsCopilot = 1 in both machine and user WindowsCopilot policy keys\nStops the Copilot app/sidebar from being invoked system-wide. Does not remove the taskbar icon by itself — combine with the taskbar setting if you want it gone visually too."),
            E("Privacy","🚫",true,"Priv_HostsBlock",
                "Block Telemetry Hosts",
                "Adds 35 Microsoft telemetry domains to the hosts file (0.0.0.0)",
                "Appends 35 entries to C:\\Windows\\System32\\drivers\\etc\\hosts\nNote: Microsoft Defender may flag this as SettingsModifier:Win32/HostsFileHijack and offer to revert it — that's expected for any hosts-file telemetry block."),

            E("Responsiveness","🖱",true,"Resp_MenuDelay",
                "Instant Menu Show",
                "Sets menu open delay to 0 ms for snappier menus",
                "Sets MenuShowDelay = 0 in HKCU\\Control Panel\\Desktop"),
            E("Responsiveness","⚡",true,"Resp_AppKill",
                "Fast App Kill Timeout",
                "Reduces wait time before force-killing frozen apps",
                "Sets WaitToKillAppTimeout = 2000ms, HungAppTimeout = 1000ms"),
            E("Responsiveness","⏹",true,"Resp_ServiceKill",
                "Fast Service Kill Timeout",
                "Cuts shutdown wait for slow-stopping services",
                "Sets WaitToKillServiceTimeout = 2000ms (machine-wide)"),
            E("Responsiveness","🔚",true,"Resp_AutoEndTasks",
                "Auto End Tasks on Shutdown",
                "Automatically kills hung apps instead of prompting",
                "Sets AutoEndTasks = 1 in HKCU\\Control Panel\\Desktop"),
            E("Responsiveness","⏱",true,"Resp_PlatformTick",
                "Platform Tick (High-Res Timer)",
                "Forces constant-rate high-resolution system timer",
                "bcdedit /set useplatformtick yes + bcdedit /set useplatformclock no\nForces the constant-rate platform tick AND disables the HPET platform clock override — the full two-part tweak for minimum timer latency."),
            E("Responsiveness","💡",true,"Resp_WinTips",
                "Disable Windows Tips",
                "Stops the 'Did you know...' popups and suggestions",
                "Sets SoftLandingEnabled = 0 in ContentDeliveryManager"),
            E("Responsiveness","📰",true,"Resp_SuggestedContent",
                "Disable Suggested Content",
                "Removes app install suggestions from the Start menu",
                "Sets SubscribedContent-338389Enabled = 0 in ContentDeliveryManager"),

            E("Gaming","🖥",false,"Game_HAGS",
                "Enable HAGS",
                "Hardware-Accelerated GPU Scheduling — reduces GPU latency",
                "Sets HwSchMode = 2 in HKLM\\...\\GraphicsDrivers"),
            E("Gaming","🎮",false,"Game_GameMode",
                "Enable Game Mode",
                "Tells Windows to prioritize foreground game processes",
                "Sets AllowAutoGameMode = 1, AutoGameModeEnabled = 1 in GameBar registry"),
            E("Gaming","🖱",false,"Game_MouseAccel",
                "Disable Mouse Acceleration",
                "Removes pointer precision for 1:1 raw mouse input",
                "Sets MouseSpeed = 0, MouseThreshold1 = 0, MouseThreshold2 = 0"),
            E("Gaming","⚡",false,"Game_CPUPriority",
                "CPU Foreground Priority Boost",
                "Increases CPU time slice for the active window/game",
                "Sets Win32PrioritySeparation = 38 in PriorityControl"),
            E("Gaming","📹",false,"Game_DVR",
                "Disable Game DVR / Capture",
                "Turns off Xbox Game Bar background recording",
                "Sets AppCaptureEnabled = 0 (user) + AllowGameDVR = 0 (policy)"),
            E("Gaming","🪟",false,"Game_FSO",
                "Disable Fullscreen Optimisations",
                "Forces exclusive fullscreen for lower input latency",
                "Sets GameDVR_FSEBehaviorMode = 2, GameDVR_HonorUserFSEBehaviorMode = 1"),
            E("Gaming","🎯",false,"Game_GPUPower",
                "GPU Power: Prefer Maximum Performance",
                "Sets D3D power policy to never downclock the GPU",
                "Sets PerfLevelSrc = 0x3322 in the D3D GPU class driver key"),
            E("Gaming","🟢",false,"Game_NvidiaTelemetry",
                "Disable NVIDIA Telemetry Services",
                "Stops NvTelemetryContainer & NvDisplayContainerLS phoning home",
                "Disables services NvTelemetryContainer, NvDisplayContainerLS + 3 NVIDIA scheduled tasks"),

            E("Network","📶",false,"Net_Nagle",
                "Disable Nagle's Algorithm",
                "Reduces TCP packet buffering — lowers game ping",
                "Sets TcpAckFrequency = 1, TCPNoDelay = 1 on all network adapter subkeys"),
            E("Network","🔁",false,"Net_RSS",
                "Enable Receive-Side Scaling",
                "Spreads network processing across CPU cores",
                "Runs: netsh int tcp set global rss=enabled"),
            E("Network","🎛",false,"Net_TCPAutoTune",
                "TCP Auto-Tuning: Normal",
                "Enables adaptive TCP receive buffer scaling",
                "Runs: netsh int tcp set global autotuninglevel=normal"),
            E("Network","🚦",false,"Net_Throttle",
                "Disable Network Throttling Index",
                "Removes multimedia network rate caps",
                "Sets NetworkThrottlingIndex = 0xFFFFFFFF in Multimedia\\SystemProfile"),
            E("Network","🏎",false,"Net_MMResponsive",
                "Max Multimedia Responsiveness",
                "Sets SystemResponsiveness to 0 for games/audio",
                "Sets SystemResponsiveness = 0 + tunes MMCSS Games & Pro Audio task priorities\nAlso sets GPU Priority = 8, Priority = 6, SchedulingCategory = High for both Games and Pro Audio tasks — reduces audio DPC latency alongside game thread scheduling."),
            E("Network","🔐",false,"Net_DoH",
                "DNS over HTTPS (Cloudflare 1.1.1.1)",
                "Enables DoH via Windows DNS Client, routes queries encrypted",
                "Sets EnableAutoDoh = 2, registers 1.1.1.1 and 1.0.0.1 with Cloudflare DoH template"),

            E("Bloatware","📰",false,"Bloat_Bing",
                "Remove Bing News & Weather",
                "Uninstalls BingNews and BingWeather UWP packages",
                "Runs Remove-AppxPackage for *BingNews*, *BingWeather*, *BingSearch* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),
            E("Bloatware","🎵",false,"Bloat_Zune",
                "Remove Zune Music / Video",
                "Removes the legacy Groove Music and Movies & TV apps",
                "Runs Remove-AppxPackage for *ZuneVideo*, *ZuneMusic* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),
            E("Bloatware","♟",false,"Bloat_Solitaire",
                "Remove Solitaire Collection",
                "Uninstalls the ad-supported Solitaire game suite",
                "Runs Remove-AppxPackage for *SolitaireCollection* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),
            E("Bloatware","🗺",false,"Bloat_Maps",
                "Remove Windows Maps",
                "Strips the built-in Maps UWP application",
                "Runs Remove-AppxPackage for *WindowsMaps* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),
            E("Bloatware","📱",false,"Bloat_PhoneLink",
                "Remove Phone Link / Your Phone",
                "Removes the Android phone companion app",
                "Runs Remove-AppxPackage for *YourPhone*, *PhoneLink* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),
            E("Bloatware","🎬",false,"Bloat_Clipchamp",
                "Remove Clipchamp",
                "Removes the bundled Microsoft video editor",
                "Runs Remove-AppxPackage for *Clipchamp* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),
            E("Bloatware","🎮",false,"Bloat_Xbox",
                "Remove Xbox Apps & Overlays",
                "Strips Xbox TCUI, App, GameOverlay, GamingOverlay",
                "Runs Remove-AppxPackage for *Xbox.TCUI*, *XboxApp*, *XboxGameOverlay*, *XboxGamingOverlay* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),
            E("Bloatware","🛒",false,"Bloat_AdTiles",
                "Remove Third-Party Ad Tiles",
                "Removes LinkedIn, Disney, Spotify, TikTok, Instagram tiles",
                "Runs Remove-AppxPackage for *LinkedIn*, *Disney*, *Spotify*, *TikTok*, *Instagram*, *Facebook* (user + provisioned)\n⚠ Cannot be undone — reinstall from respective app stores if needed."),
            E("Bloatware","📦",false,"Bloat_Office",
                "Remove Office Hub & OneNote",
                "Uninstalls the bundled Office Hub and OneNote UWP apps",
                "Runs Remove-AppxPackage for *OfficeHub*, *OneNote* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed. Does NOT affect desktop Office installs."),
            E("Bloatware","🗃",false,"Bloat_3D",
                "Remove 3D Viewer & Print 3D",
                "Removes legacy 3D apps nobody asked for",
                "Runs Remove-AppxPackage for *3DViewer*, *Print3D* (user + provisioned)\n⚠ Cannot be undone — reinstall from Microsoft Store if needed."),

            E("Security","🔇",false,"Sec_AutoRun",
                "Disable AutoRun / AutoPlay",
                "Blocks autorun.inf and AutoPlay on all drive types",
                "Sets NoDriveTypeAutoRun = 0xFF at user + machine scope, blocks autorun.inf via IniFileMapping"),
            E("Security","🖥",false,"Sec_RDP",
                "Disable Remote Desktop (RDP)",
                "Refuses all inbound RDP connections, closes firewall rule",
                "Sets fDenyTSConnections = 1 + disables 'Remote Desktop' firewall rule group"),
            E("Security","🪟",false,"Sec_SMBv1",
                "Disable SMBv1",
                "Removes the WannaCry/EternalBlue-vulnerable SMBv1 protocol",
                "Runs Set-SmbServerConfiguration -EnableSMB1Protocol $false + Disable-WindowsOptionalFeature SMB1Protocol\nSMBv1 is the protocol exploited by WannaCry ransomware. Modern Windows uses SMBv2/3. Safe to disable on any modern system."),
            E("Security","📡",false,"Sec_NetBIOS",
                "Disable NetBIOS over TCP/IP",
                "Stops NetBIOS on all adapters — prevents NBNS poisoning",
                "Runs SetTcpipNetbios(2) on all WMI network adapter configs\nNetBIOS broadcasts your machine name on the network and is a vector for NBNS/LLMNR poisoning attacks. No practical use on modern networks."),
            E("Security","🛡",false,"Sec_Defender",
                "Ensure Defender Real-Time Protection",
                "Forces Defender real-time monitoring ON via policy + cmdlet",
                "Sets DisableAntiSpyware = 0, DisableRealtimeMonitoring = 0 + runs Set-MpPreference -DisableRealtimeMonitoring $false"),

            Adv("⚙","ProcessorScheduling","Adv_ProcessorScheduling",
                "Processor Scheduling: Programs",
                "Win32PrioritySeparation=38, max foreground CPU boost",
                "Sets Win32PrioritySeparation = 38 in PriorityControl"),
            Adv("⏱","DisableDynamicTick","Adv_DynamicTick",
                "Disable Dynamic Tick",
                "Forces constant high-res IRQ8 timer, reduces micro-stutter",
                "Runs: bcdedit /set disabledynamictick yes"),
            Adv("🔥","DisableCpuThrottling","Adv_CPUThrottle",
                "Disable CPU Throttling",
                "Prevents Windows pulling background process CPU clocks",
                "Sets ValueMax = 0 in THROTTLE_POLICY key + powercfg PERFAUTONOMOUS = 0"),
            Adv("💾","EnableTrim","Adv_TRIM",
                "Ensure SSD TRIM Enabled",
                "Sets disabledeletenotify=0, keeps SSD write speeds consistent",
                "Runs: fsutil behavior set disabledeletenotify 0"),
            Adv("🎨","AggressiveAnimations","Adv_Animations",
                "Aggressive Animation Disabling",
                "Kills UserPreferencesMask, TaskbarAnim, MinAnimate bits",
                "Sets UserPreferencesMask binary value + TaskbarAnimations = 0, MinAnimate = 0, ListviewShadow = 0"),

            // ── New Advanced tweaks (route through ApplyTweak via TweakKey) ───────────────────
            E("Advanced","🅿️",false,"Adv_CoreParking",
                "Disable CPU Core Parking",
                "Forces all CPU cores to stay active — prevents park-induced stutter",
                "powercfg CPMINCORES → 100 (AC + DC) on current power plan\nWindows 11 parks idle cores to save power. On desktops this can cause micro-stutters, especially on Intel 12th–14th gen. Setting CPMINCORES=100 prevents any core from being parked."),
            E("Advanced","📨",false,"Adv_MsiMode",
                "Enable MSI Mode (GPU)",
                "Switches GPU interrupts from legacy line-based to Message Signaled",
                "Sets MSISupported = 1 under Enum\\PCI\\<GPU>\\Device Parameters\\Interrupt Management\\MessageSignaledInterruptProperties\nMSI mode routes GPU interrupts more efficiently, reducing DPC latency vs. legacy line-based interrupt mode. Applied to every display adapter (iGPU + dGPU). Most modern GPUs already default to MSI."),
            E("Advanced","📬",false,"Adv_IrqAffinity",
                "IRQ Affinity — Spread GPU Interrupts",
                "Sets GPU DevicePolicy to spread MSI-X interrupts across all P-cores",
                "Sets DevicePolicy = 5 (IrqPolicySpreadMessagesAcrossAllProcessors) in each GPU's Interrupt Management\\Affinity Policy\nFor MSI-X capable GPUs — distributes interrupt handling across all processor cores instead of pinning to core 0."),
            E("Advanced","🕐",false,"Adv_TscSync",
                "TSC Sync Policy: Legacy",
                "Forces legacy TSC synchronisation — reduces scheduling jitter",
                "bcdedit /set tscsyncpolicy legacy\nThe TSC (Time Stamp Counter) sync policy controls how Windows synchronises high-res timers across cores. Legacy mode can reduce micro-jitter on multi-core systems."),
            E("Advanced","📣",false,"Adv_X2Apic",
                "Enable x2APIC Mode",
                "Enables x2APIC interrupt controller — improves handling on many-core CPUs",
                "bcdedit /set x2apicpolicy enable\nx2APIC extends the legacy APIC interrupt controller to support more than 255 logical processors and improves interrupt delivery efficiency. Most beneficial on HEDT and Ryzen systems with many cores."),
            E("Advanced","🚀",false,"Adv_BoostMode",
                "Unhide Processor Boost Mode",
                "Reveals the hidden Boost Mode dropdown in Advanced Power Settings",
                "Sets Attributes = 2 on the PERFBOOSTMODE setting definition (HKLM\\SYSTEM\\...\\Power\\PowerSettings\\54533251-...\\be337238-...)\nThis is a Microsoft-documented but hidden power setting. It doesn't force a boost value — it just makes 'Processor performance boost mode' visible under Control Panel → Power Options → Change plan settings → Change advanced power settings → Processor power management, so you can pick Aggressive / Efficient Aggressive / etc. yourself, per plan and per AC/DC state. Safe and fully reversible — undo re-hides it."),

            // ── New Privacy tweaks ────────────────────────────────────────────────────
            E("Privacy","☁️",true,"Priv_CloudContent",
                "Disable Cloud Content & Delivery Manager",
                "Kills Spotlight ads, silent app installs, lock screen tips",
                "Sets DisableWindowsConsumerFeatures = 1 in CloudContent policy + disables 7 ContentDeliveryManager values\nControls Windows Spotlight (lock screen ads), suggested apps in Start, silent background app installs, and OEM pre-installed app promotions."),

            // ── New Responsiveness tweaks ──────────────────────────────────────────────
            E("Responsiveness","📋",false,"Resp_VerboseStatus",
                "Verbose Boot/Shutdown Status",
                "Shows real service names during boot and shutdown instead of spinner",
                "Sets verbosestatus = 1 in HKLM\\...\\Policies\\System\nReplaces the generic spinning circle with real-time text showing which services are starting or stopping. Not a performance tweak — useful diagnostic tool for power users."),

            // ── New Network tweaks ────────────────────────────────────────────────────────────
            E("Network","📦",false,"Net_LargeOffload",
                "Disable Large Send Offload (LSO)",
                "Disables LSO v2 on all physical adapters — reduces NIC-driver jitter",
                "Set-NetAdapterAdvancedProperty LSO V2 (IPv4/IPv6) → Disabled on all physical adapters\nLSO lets the NIC batch large sends, but some drivers introduce inconsistent latency doing so. Disabling forces the CPU to handle segmentation, which is more predictable on modern hardware."),
            E("Network","⏳",false,"Net_TcpTimedWait",
                "Reduce TCP TIME_WAIT Delay",
                "Cuts TIME_WAIT connection hold from 240s to 30s",
                "Sets TcpTimedWaitDelay = 30 in HKLM\\...\\Tcpip\\Parameters\nWindows holds closed TCP connections in TIME_WAIT for 240 seconds by default. Reducing to 30s frees ports faster on systems making many short-lived connections (game launchers, streaming, APIs)."),

            // ── v1.5 additions ─────────────────────────────────────────────────────
            E("Performance","🧩",true,"Perf_Widgets",
                "Disable Widgets Board",
                "Removes the Widgets panel and its background WebView processes",
                "Sets AllowNewsAndInterests = 0 in HKLM\\SOFTWARE\\Policies\\Microsoft\\Dsh\nWidgets keeps several Edge WebView2 processes alive in the background for news/weather feeds, costing RAM and CPU wake-ups. The policy removes the board and the taskbar button."),
            E("Privacy","🎯",true,"Priv_TailoredExp",
                "Disable Tailored Experiences",
                "Stops Microsoft using diagnostic data for personalised tips and ads",
                "Sets TailoredExperiencesWithDiagnosticDataEnabled = 0 (user) + DisableTailoredExperiencesWithDiagnosticData = 1 (policy)"),
            E("Privacy","✍",true,"Priv_InkTyping",
                "Disable Inking & Typing Data Collection",
                "Stops Windows harvesting what you type and ink to build a personal dictionary",
                "Sets RestrictImplicitInkCollection = 1, RestrictImplicitTextCollection = 1, HarvestContacts = 0, AcceptedPrivacyPolicy = 0\nSame as Settings → Privacy → Inking & typing personalization → Off."),
            E("Responsiveness","📋",false,"Resp_ClassicContext",
                "Classic Right-Click Menu",
                "Brings back the full Windows 10 context menu — no more 'Show more options'",
                "Creates HKCU\\Software\\Classes\\CLSID\\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\\InprocServer32 with an empty default value\nThe Win11 compact menu adds a click (and a noticeable delay) for most shell extensions. Undo deletes the key. Needs an Explorer restart."),
            E("Responsiveness","🛑",false,"Resp_EndTask",
                "Add 'End Task' to Taskbar",
                "Right-click a taskbar app → End task, no Task Manager needed",
                "Sets TaskbarEndTask = 1 in Explorer\\Advanced\\TaskbarDeveloperSettings\nBuilt-in Windows 11 23H2+ feature normally hidden under Settings → System → For developers."),
            E("Gaming","⌨",false,"Game_StickyKeys",
                "Disable Sticky / Filter Keys Hotkeys",
                "Stops the 5×Shift popup from yanking you out of games",
                "Sets StickyKeys Flags = 506, ToggleKeys Flags = 58, Keyboard Response Flags = 122\nOnly the keyboard shortcuts are disabled — the accessibility features themselves still work from Settings."),
            E("Network","📤",false,"Net_DeliveryOpt",
                "Disable Delivery Optimization P2P",
                "Stops Windows uploading updates to other PCs over your connection",
                "Sets DODownloadMode = 0 (HTTP only) in DeliveryOptimization policy\nUpdates still download normally from Microsoft — your PC just stops seeding them to LAN/internet peers."),

            // ── LAPTOP (battery life) ──────────────────────────────────────────────
            // Power-plan tweaks change only the ON BATTERY (DC) side of the active plan —
            // plugged-in performance is untouched. All are undoable.
            E("Laptop","🪫",false,"Lap_EnergySaver",
                "Energy Saver at 30%",
                "Turns on Energy Saver at 30% instead of 20% and dims the screen harder",
                "powercfg: Energy Saver → Charge level (ESBATTTHRESHOLD) = 30, Display brightness weight (ESBRIGHTNESS) = 50 on battery\nEnergy Saver throttles background activity, sync and notifications. Kicking in earlier buys the most time for the least effort."),
            E("Laptop","🐢",false,"Lap_NoTurbo",
                "Disable Turbo Boost on Battery",
                "Stops CPU boost clocks when unplugged — big battery + heat win",
                "powercfg: Processor performance boost mode (PERFBOOSTMODE) = Disabled on battery\nBoost clocks cost disproportionately more power than they give back. Typical result: 15–30% longer battery on light work, cooler and quieter. Plugged-in boost is unaffected."),
            E("Laptop","🍃",false,"Lap_CpuEfficiency",
                "CPU Energy Preference: Efficiency",
                "Tells the CPU to favour efficiency over speed when unplugged",
                "powercfg: Energy performance preference (PERFEPP) = 80% on battery (+ E-cores on hybrid CPUs)\n0 = max performance, 100 = max efficiency. Balanced defaults to ~50 on battery. Intel Speed Shift / AMD CPPC use this hint to pick clocks."),
            E("Laptop","🌙",false,"Lap_ScreenSleep",
                "Shorter Screen & Sleep Timeouts",
                "Screen off after 3 min, sleep after 10 min on battery",
                "powercfg: VIDEOIDLE = 180s, STANDBYIDLE = 600s on battery\nThe display is the single biggest battery drain. Only shortens timeouts — if yours are already lower they're left alone."),
            E("Laptop","🔆",false,"Lap_AdaptiveBright",
                "Adaptive Brightness on Battery",
                "Lets the ambient light sensor lower brightness when unplugged",
                "powercfg: Enable adaptive brightness (ADAPTBRIGHT) = On for battery\nNo effect on laptops without an ambient light sensor."),
            E("Laptop","🔌",false,"Lap_PcieAspm",
                "PCIe Link Power: Maximum Savings",
                "Lets NVMe, Wi-Fi and GPU links drop into low-power states on battery",
                "powercfg: PCI Express → Link State Power Management (ASPM) = Maximum power savings on battery\nOne of the biggest idle-drain fixes on laptops with a dGPU. Very rarely an old NVMe drive or Wi-Fi card misbehaves — Undo restores it."),
            E("Laptop","📶",false,"Lap_WifiPowerSave",
                "Wi-Fi Maximum Power Saving",
                "Puts the wireless adapter in its deepest power-save mode on battery",
                "powercfg: Wireless Adapter Settings → Power Saving Mode = Maximum Power Saving on battery\nCan add a little latency to online games or calls on battery — plugged-in Wi-Fi is unaffected."),
            E("Laptop","🔋",false,"Lap_UsbSuspend",
                "USB Selective Suspend on Battery",
                "Idle USB devices power down when unplugged",
                "powercfg: USB selective suspend = Enabled on battery\nWindows default, but many 'gaming' tweak packs switch it off — this puts it back."),
            E("Laptop","⏰",false,"Lap_WakeTimers",
                "Disable Wake Timers on Battery",
                "Stops scheduled tasks & updates waking the laptop in your bag",
                "powercfg: Allow wake timers (RTCWAKE) = Disable on battery\nPrevents the classic 'hot laptop in a backpack' from maintenance tasks waking a sleeping machine."),
            E("Laptop","📴",false,"Lap_StandbyNetwork",
                "No Network in Modern Standby",
                "Disconnects Wi-Fi while asleep on battery (Modern Standby laptops)",
                "powercfg: Networking connectivity in Standby = Disable on battery\nModern Standby (S0) laptops otherwise stay online while 'asleep' to sync mail and updates — a major overnight drain. Not supported on S3-sleep machines (reported as not supported)."),
            E("Laptop","🎬",false,"Lap_VideoBattery",
                "Video Playback: Optimise for Battery",
                "Uses power-saving video processing when watching on battery",
                "powercfg: Multimedia → When playing video = Optimize power savings, Video playback quality bias = Power-saving on battery"),
            E("Laptop","💾",false,"Lap_CritHibernate",
                "Hibernate on Critical Battery",
                "Saves your session to disk instead of dying at 0%",
                "powercfg: Critical battery action (BATACTIONCRIT) = Hibernate on battery\nRequires hibernation — conflicts with Performance → Disable Hibernation, and will refuse (not silently re-enable) if hibernation is off."),
            E("Laptop","🔍",false,"Lap_IndexOnBattery",
                "Pause Search Indexing on Battery",
                "Search indexer waits until you're plugged in",
                "Sets PreventIndexOnBattery = 1 in HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\nKeeps Windows Search working (unlike disabling the service) but stops the disk + CPU churn of indexing while unplugged."),
            E("Laptop","🚫",false,"Lap_BackgroundApps",
                "Block Background Store Apps",
                "Stops Store/UWP apps running in the background (all power states)",
                "Sets LetAppsRunInBackground = 2 (Force Deny) in AppPrivacy policy\nApplies on AC too. Apps like Mail, Phone Link or Teams (Store version) won't get live notifications until opened. Desktop apps are unaffected."),
            E("Laptop","🌐",false,"Lap_EdgeBackground",
                "Stop Edge Running in Background",
                "Disables Edge Startup Boost and keep-running-after-close",
                "Sets StartupBoostEnabled = 0, BackgroundModeEnabled = 0 in HKLM\\SOFTWARE\\Policies\\Microsoft\\Edge\nEdge otherwise preloads at sign-in and keeps processes alive after you close it, even if you never use it. Applies on AC too."),
            E("Laptop","🪟",false,"Lap_Transparency",
                "Disable Transparency Effects",
                "Turns off Mica/acrylic blur — less GPU work on every frame",
                "Sets EnableTransparency = 0 in HKCU\\...\\Themes\\Personalize\nSame as Settings → Personalization → Colors → Transparency effects → Off. Applies on AC too."),
        };

        // Single display/run order for categories — used by the grid, the run loop and the CLI
        public static readonly string[] CategoryOrder =
        {
            "Performance", "Privacy", "Responsiveness",
            "Gaming", "Network", "Bloatware", "Security", "Advanced", "Laptop"
        };

        public static int OrderOf(string cat) => Array.IndexOf(CategoryOrder, cat);

        public static IEnumerable<TweakEntry> ForCategory(string cat) =>
            cat == "All" ? All : All.Where(t => t.Category == cat);
    }
}
